if: tag IS present
language: cpp
compiler: gcc
os:
  - linux
  - osx
arch:
  - amd64
  - arm64
dist: bionic
osx_image: xcode12
addons:
  homebrew:
    packages:
      - qt5
      - qwt
    update: true
  apt:
    packages:
      - qt5-default
      - libqwt-qt5-dev
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - libusb-1.0-0-dev
script:
  - python build.py
deploy:
  provider: releases
  api_key:
    secure: "WGy+JMxmzWwWGUeiu6nMxA5sfiZwb2X7xWsn1QQjmmiVYgNLVmYk7DE9ejohrUXl3taivD4Oy3hxXt0NTCv/UIvTlaG+TZw4VV9n4cfnw8CuBlpncaqS0g1bj9RNGK9kHFxLEPtwQ8gTX2vrgcTAyuRcn7cwjokm991vbHSHYGGUvI0LV18ljExyMJ3ysFX+Uy9CiTULawwwzgTWYlXudUoUTDz7tyqM3LYgJfaMUIbRhl5yfHis0Ht0EIOdLV0Ah7V2K5YqSMxTg1agJYT1iOIk3CHCdbqawdSiO9Z3dstWYps4njsH1Y6suCYrZpJav2B6TLQZ1IVz+0IiEAY0jysyhITjxL0bojEx8rvJ/MehFcXOlUrWO+UhK+92uFHhiWnk1WOQUy6LtDDP5dUs5fdrBbEi+VFV0EbuMXbU90dqol4TGJ4az0vlxiGen0b3c5XkoxfxIzW89KiyiWpwu3Db3oCp6zpTlooWtHuhol7slSEZRwaOjQgayLJkteImyvwcu3gPVuiglRQXWEy1QkXX8fcpGSgx8JfJjYj/7p6P1UKrfzPkook9MfMecsK74qkSjdlqN7WtK9uYireeJZxLXnrGxHi8oX0F/hig+72GhyjHSReOoER23X1i3PzZ7dzDR9G6tuU19Vjtd3n2bW2w0USAwbMGSAukD+U2Nk8="
  file_glob: true
  file: "Lenlab-*"
  skip_cleanup: true
  on:
    tags: true
