skip_non_tags: true
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS
build_script:
  - python build.py
test: off
artifacts:
  - path: 'Lenlab-*-win64.zip'
  - path: 'Lenlab-*-x86_64.AppImage'
  - path: 'Lenlab-*-mac.dmg'
deploy:
  provider: GitHub
  auth_token:
    secure: 1jImAYiBl0QnfhjcWQIZJCu4egVYVbkB3A2yS3EBD3SxoPA3Gq65hy18n6kaAOh9
  force_update: true
  prerelease: true
