branches:
  only:
    - main
image:
  - Ubuntu
  - macOS
  - Visual Studio 2022
build_script:
  - cmd: C:\Python311-x64\python -u build.py
  - sh: $HOME/venv3.11/bin/python build.py
artifacts:
  - path: 'Lenlab-*-linux-x86_64.AppImage'
  - path: 'Lenlab-*-mac.dmg'
  - path: 'Lenlab-*-win.zip'
deploy:
  - provider: GitHub
    auth_token:
      secure: Rn2tlQInPnKQ7HKltu/iBMPA2jT+56K+unEX91TUcA0THU0u1ktko5d/9fSEfqCk
    prerelease: true
    on:
      APPVEYOR_REPO_TAG: true
